nn4
KI-Vorlesung/Lecture pull request #117
Opened 2021-12-07 11:12 UTC by cyildiz

add videos, notes, recap, reading and outcomes

2021-12-07 11:20 UTC, cyildiz commented
@cagix , ich habe ein neues buch in ki.bib hinzugefügt und diese im recap referenziert.
Es scheint die gleiche Form wie in Deinen Notizen zu haben, wird aber nicht richtig verlinkt. Siehst Du, wo der Fehler liegt?

2021-12-07 11:56 UTC, cagix requested changes
Sieht gut aus -- die letzte Formel hat das selbe Tag wie die erste (siehe Kommentare). Zusätzlich würde ich noch die eckigen Klammern mit den `\lbrack` bzw. `\rbrack` ersetzen; zumindest  mit den geschweiften Klammern kommt Hugo immer nicht richtig klar ...

2021-12-07 11:56 UTC, cagix commented on markdown/ml/ml4_overfitting/index.md
> +    $$ w_j := w_j - \frac{\alpha}{m} \left[ \sum_{i=1}^m \left( ( a^{[i]} - y^{[i]} )x_j^{[i]} \right) + \lambda w_j  \right] \tag{1} $$
```suggestion
    $$ w_j := w_j - \frac{\alpha}{m} \left[ \sum_{i=1}^m \left( ( a^{[i]} - y^{[i]} )x_j^{[i]} \right) + \lambda w_j  \right] \tag{2} $$
```

2021-12-07 11:56 UTC, cagix commented on markdown/ml/ml4_overfitting/index.md
> +    $$ J = \frac{1}{m} \left[ \sum_{i=1}^m \left( -y^{[i]}log(a^{[i]})-(1-y^{[i]})log(1-a^{[i]}) \right) + \frac{\lambda}{2} \sum_{j=1}^n (w^2_j)  \right] \tag{1} $$
```suggestion
    $$ J = \frac{1}{m} \left\lbrack \sum_{i=1}^m \left( -y^{[i]}log(a^{[i]})-(1-y^{[i]})log(1-a^{[i]}) \right) + \frac{\lambda}{2} \sum_{j=1}^n (w^2_j)  \right\rbrack \tag{1} $$
```

2021-12-07 11:56 UTC, cagix commented on markdown/ml/ml4_overfitting/index.md
> +    $$ w_j := w_j - \frac{\alpha}{m} \left[ \sum_{i=1}^m \left( ( a^{[i]} - y^{[i]} )x_j^{[i]} \right) + \lambda w_j  \right] \tag{1} $$
```suggestion
    $$ w_j := w_j - \frac{\alpha}{m} \left\lbrack \sum_{i=1}^m \left( ( a^{[i]} - y^{[i]} )x_j^{[i]} \right) + \lambda w_j  \right\rbrack \tag{1} $$
```

2021-12-07 11:57 UTC, cagix commented
> @cagix , ich habe ein neues buch in ki.bib hinzugefügt und diese im recap referenziert.
> Es scheint die gleiche Form wie in Deinen Notizen zu haben, wird aber nicht richtig verlinkt. Siehst Du, wo der Fehler liegt?

Ich habe grad mal `make clean web` gemacht -- und das Buch ist in der Literaturliste :)

<img width="1347" alt="Screenshot 2021-12-07 at 12 49 40" src="https://user-images.githubusercontent.com/20356276/145025003-8388a6bf-2fb7-4fe8-b756-f105b14a5e8b.png">

2021-12-07 15:32 UTC, cagix commented
> @cagix , ich habe ein neues buch in ki.bib hinzugefügt und diese im recap referenziert.
> Es scheint die gleiche Form wie in Deinen Notizen zu haben, wird aber nicht richtig verlinkt. Siehst Du, wo der Fehler liegt?

@cyildiz Hattest Du evtl. noch die "alte" Webseite aus einem vorigen Lauf herumliegen? Es kann gut sein, dass aus dem `.bib`-File kein neues `readings.yaml` generiert wird, wenn das `readings.yaml` noch/schon existiert (das Makefile ist etwas buggy, @jposselt baut drüben in https://github.com/Compilerbau/Lecture/pull/107 grad eine ordentliche Version 🥇) ... ein `make clean web` sollte dann aber die gewünschte Ausgabe erstellen.

2021-12-08 18:30 UTC, cyildiz commented
> ein `make clean web` sollte dann aber die gewünschte Ausgabe erstellen.

das habe ich jetzt gemacht. die liste unten erscheint, aber der link im text stimmt nicht:

<img width="769" alt="image" src="https://user-images.githubusercontent.com/1532767/145263910-21a413a4-4497-4df2-8433-e842c0dc546a.png">

2021-12-08 19:12 UTC, cagix commented
> > ein `make clean web` sollte dann aber die gewünschte Ausgabe erstellen.
> 
> das habe ich jetzt gemacht. die liste unten erscheint, aber der link im text stimmt nicht:
> 
> <img alt="image" width="769" src="https://user-images.githubusercontent.com/1532767/145263910-21a413a4-4497-4df2-8433-e842c0dc546a.png">

oh, mift ... die index.md muss dafür von pandoc vorverarbeitet werden. d.h. die muss noch im makefile eingetragen werden: Füge mal bitte im Makefile eine neue Zeile `SRC   += ml/ml4_overfitting` zwischen Zeile 100 und 101 ein. Dann sollte es auch im Text aufgelöst werden.

2021-12-08 20:15 UTC, cyildiz commented
> Füge mal bitte im Makefile eine neue Zeile `SRC += ml/ml4_overfitting` zwischen Zeile 100 und 101 ein. Dann sollte es auch im Text aufgelöst werden.

Hat geklappt, danke!

2021-12-09 05:39 UTC, cagix approved these changes
lgtm :)

2021-12-09 05:41 UTC, merged