nn5
KI-Vorlesung/Lecture pull request #119
Opened 2021-12-07 18:31 UTC by cyildiz

add video, notes and outcomes for nn5

2021-12-07 18:37 UTC, cyildiz commented
@cagix , ich weiss nicht genau, ob ich Multilayerperzeptron verwenden soll, oder Multi-Layer Perzeptron?

Ich werde diese Woche NN4 und NN5 gemeinsam online stellen. Das sollte ich auch im Fahrplan eintragen, oder? Müsste ich diesbezüglich noch etwas machen?

2021-12-07 19:03 UTC, cagix commented
> @cagix , ich weiss nicht genau, ob ich Multilayerperzeptron verwenden soll, oder Multi-Layer Perzeptron?

Hmmm, gute Frage. Ich schreibe immer "MLP" :)


> Ich werde diese Woche NN4 und NN5 gemeinsam online stellen. 

Können wir gern so machen. Sobald die beiden Branches gemergt sind, aktualisiere ich die Webseite im ILIAS. D.h. das Mergen ist der Trigger fürs Online-Stellen :)


> Das sollte ich auch im Fahrplan eintragen, oder? Müsste ich diesbezüglich noch etwas machen?

Wieso? Die Vorlesungen sind doch den Wochen zugeordnet, wo die Themen inhaltlich dran sind. Wir hatten in der Vergangenheit ja auch nicht geschrieben, wenn irgendwas aktualisiert wurde?

2021-12-07 19:05 UTC, cagix approved these changes
LGTM 👍

2021-12-07 19:36 UTC, cyildiz commented
> Wieso? Die Vorlesungen sind doch den Wochen zugeordnet, wo die Themen inhaltlich dran sind. Wir hatten in der Vergangenheit ja auch nicht geschrieben, wenn irgendwas aktualisiert wurde?

Die Inhalte in NN4-Overfitting sind zu wenig für eine Woche. NN4 und NN5 bilden gemeinsam die  Inhalte für KW50 (ähnlich wie bei Deiner KW42).
Sollte ich das ganze vielleicht lieber in eine NN4-Seite packen, und die zwei PDF-Dateien NN4.1 und NN4.2 nennen?

2021-12-07 20:13 UTC, cagix commented
> > Wieso? Die Vorlesungen sind doch den Wochen zugeordnet, wo die Themen inhaltlich dran sind. Wir hatten in der Vergangenheit ja auch nicht geschrieben, wenn irgendwas aktualisiert wurde?
> 
> Die Inhalte in NN4-Overfitting sind zu wenig für eine Woche. NN4 und NN5 bilden gemeinsam die Inhalte für KW50 (ähnlich wie bei Deiner KW42). Sollte ich das ganze vielleicht lieber in eine NN4-Seite packen, und die zwei PDF-Dateien NN4.1 und NN4.2 nennen?

ah, verstehe ... ja, dann sollten wir das am besten einfach in der `data/schedule.yaml` passend eintragen, oder?

2021-12-07 20:16 UTC, cagix commented
> > Die Inhalte in NN4-Overfitting sind zu wenig für eine Woche. NN4 und NN5 bilden gemeinsam die Inhalte für KW50 (ähnlich wie bei Deiner KW42). Sollte ich das ganze vielleicht lieber in eine NN4-Seite packen, und die zwei PDF-Dateien NN4.1 und NN4.2 nennen?
> 
> ah, verstehe ... ja, dann sollten wir das am besten einfach in der `data/schedule.yaml` passend eintragen, oder?

dann verschiebt sich halt der rest in der planung, wenn ich das richtig sehe. brauchst du dann "nach hinten raus" noch neue themen (also auch ordner)?

2021-12-08 13:29 UTC, cyildiz commented
Ok, dann mache ich die Änderung im `schedule.yaml`.

> dann verschiebt sich halt der rest in der planung, wenn ich das richtig sehe. brauchst du dann "nach hinten raus" noch neue themen (also auch ordner)?

Mindestens einen neuen Folder werde ich dann noch brauchen. Weiss noch nicht wie das genau ausschauen wird, das werde ich erst diesen Freitag planen können.

2021-12-08 14:17 UTC, cagix requested changes
ein paar Typos und einen Ergänzungsvorschlag ...

2021-12-08 14:17 UTC, cagix commented on markdown/ml/ml5_mlp/index.md
> +menuTitle: "NN5 - Multilayer Perzeptron"
für das Menü würde ich die Kurzvariante "MLP" nehmen

2021-12-08 14:17 UTC, cagix commented on markdown/ml/ml5_mlp/index.md
> +*   Das Perzeptron kann nur lineare Funktionen modellieren.
... oder linear separable Klassen korrekt klassifizieren...

2021-12-08 14:17 UTC, cagix commented on markdown/ml/ml5_mlp/index.md
> +*   Durch das Zusammenschließen von mehreren Perzeptronen kann man ein mehrschichtiges Perzeptron (engl. Mulitlayer Perceptron) aufstellen, das komplexere Funktionen modellieren kann.
```suggestion
*   Durch das Zusammenschließen von mehreren Perzeptronen kann man ein mehrschichtiges Perzeptron (engl. Multilayer Perceptron) aufstellen, das komplexere Funktionen modellieren kann.
```

2021-12-08 14:17 UTC, cagix commented on markdown/ml/ml5_mlp/index.md
> +*   Die "inneren" Schichten eines solchen Netzerkes sind sogenannte **versteckte Schichten** (engl. hidden layer). Das sind alle Schichten ausgenommen der Eingangs- und Ausgangsschicht.
```suggestion
*   Die "inneren" Schichten eines solchen Netzwerkes sind sogenannte **versteckte Schichten** (engl. hidden layer). Das sind alle Schichten ausgenommen die Eingangs- und Ausgangsschicht. 
```

2021-12-08 14:20 UTC, cagix commented
@cyildiz Ich kenne "deep networks" immer nur mit wirklich vielen Schichten, d.h. ich würde ein MLP mit einem hidden layer noch nicht als "deep" bezeichnen. Du beziehst Dich da auf die Arbeiten von Ng, oder?

2021-12-08 18:15 UTC, cyildiz commented
> @cyildiz Ich kenne "deep networks" immer nur mit wirklich vielen Schichten, d.h. ich würde ein MLP mit einem hidden layer noch nicht als "deep" bezeichnen. Du beziehst Dich da auf die Arbeiten von Ng, oder?

Ich glaube, ich hatte etwas in der Richtung in Geron gelesen, konnte die Stelle jetzt aber nicht wieder finden. Anfangs soll man alle netzwerke mit mit mehr als einer schicht als tief bezeichnet haben, inzwischen kann aber darüber diskutiert werden, ab wann ein netzwerk als tief gelten kann. 
Ist auf jeden Fall keine "reine Tatsache", besser es wegzulassen denke ich. Danke für den Hinweis.

2021-12-09 05:47 UTC, cagix approved these changes
lgtm 👍 


"blatt08" muss noch in "sheet08" umbenannt werden, das mache ich gleich noch vor dem mergen :)

2021-12-09 05:50 UTC, merged