initial plan (see notion)
KI-Vorlesung/Lecture pull request #18
Opened 2021-09-06 08:56 UTC by cagix

fixes #15

2021-09-06 09:01 UTC, cagix commented
@cyildiz Ich habe mal unseren  Plan aus Notion hier übertragen und bei den fehlenden Inhalten (ML) erstmal nur die Startseite eingetragen. Zusätzlich habe ich die Kommentare übernommen, die können wir später wieder rauslöschen.

Man hat zwei Möglichkeiten, um auf unterschiedliche Themen für TDU bzw. FHB hinzuweisen: Entweder als "notes" direkt am "topic" oder (zusätzlich) noch einmal unter "notes" in "misc" (das geht dann in die rechte Spalte "Verschiedenes"). 

Ich würde bei den Wochen, wo unterschiedliche Inhalte dran sind, entsprechend den "topic"-Eintrag verdoppeln (einmal TDU, einmal FHB) und dabei mit "notes" kurz definieren, für wen der Inhalt ist ("nur TDU", "nur FHB"), das kommt dann direkt als Hinweis unter das Thema. Zusätzlich würde ich mit "misc"/"notes" einen Satz schreiben, der das nochmal ausführlicher erklärt. Das habe ich schon mal so angefangen, d.h. wenn Du das sinnvoll findest, könnten wir das nehmen und ausbauen :)

2021-09-08 13:05 UTC, cyildiz requested changes
Soweit alles gut.
Sollen wir diesen Branch mergen, bevor ich meine Themen im schedule aktualisiere?
Dann mache ich meine Änderungen in einem separaten feature-branch?

Ich würde einige style-Änderungen vorschlagen, um die Lesbarkeit zu erhöhen (optional):

- [ ] den Leerraum um die \<ul> Elemente in einer Tabellenzelle reduzieren.
- [ ] in der Wochenspalte den Text "Woche" weglassen.
- [ ] im schedule.html den Code so ändern, dass die "misc" Spalte einfach ein- und ausgeschaltet werden kann (mittels $ifmisc := false).
- [ ] Wenn möglich die misc-Spalte vermeiden, die Legende und/oder die VL/UE Spalten nutzen.
- [ ] Die "leader" Information ein mal in der KW-Spalte angeben (ist zum Großteil nach Wochen aufgeteilt, nach jedem Topic scheint mir zu viel Redundanz). Bei der einen Ausnahme am Anfang könnte man den Hinweis anpassen: "Gemeinsames Kick-Off mit Carsten und Canan".
- [ ] Zeilenumbruch zwischen Übungsblatt und (Abgabe xx); dadurch wird die Spalte schmaler.

Ich habe diese Änderungen bereits umgesetzt und ausprobiert und kann diese ggfl. vor dem Mergen pushen.
<img width="933" alt="image" src="https://user-images.githubusercontent.com/1532767/132521001-471502a5-c2c3-429f-9c24-b566e0204fe9.png">

2021-09-08 13:47 UTC, cagix commented
> Sollen wir diesen Branch mergen, bevor ich meine Themen im schedule aktualisiere?
> Dann mache ich meine Änderungen in einem separaten feature-branch?

Wir könnten den Branch jetzt mergen. Dann würdest Du die neuen Lectures schrittweise per Feature-Branch erstellen und einpflegen und dabei die neue Lecture dann auch in den Schedule eintragen.

Die Alternative wäre, jetzt diesen Branch zu nutzen und die restlichen Strukturen anzulegen und den Schedule anzupassen und dann erst diesen Branch zu mergen. Dann kann man die Inhalte in den Feature-Branches ergänzen.

Ich wäre eigentlich für die zweite Variante :)  Du kannst gern in diesem Branch weiterarbeiten, wenn Du das möchtest.

---

> Ich würde einige style-Änderungen vorschlagen, um die Lesbarkeit zu erhöhen (optional):
> 
> * [x]  den Leerraum um die <ul> Elemente in einer Tabellenzelle reduzieren.
> * [ ]  in der Wochenspalte den Text "Woche" weglassen.

Finde ich sinnvoll. Da der Code als Submodule in ein neues Repo ausgelagert ist: Machst Du bitte ein Ticket für die Style-Anpassungen auf und auch gleich einen PR gegen dieses andere Repo auf (https://github.com/cagix/Hugo-Lecture-Layouts)?

---

> * [ ]  im schedule.html den Code so ändern, dass die "misc" Spalte einfach ein- und ausgeschaltet werden kann (mittels $ifmisc := false).
> * [ ]  Wenn möglich die misc-Spalte vermeiden, die Legende und/oder die VL/UE Spalten nutzen.

Wenn im `schedule.yaml` keine "misc"-Informationen drin sind, wird die Spalte gar nicht erst angezeigt. Das ist schon so implementiert. Ich hatte nur im Schedule vermutlich noch was dazu drin stehen, was man vermutlich anders lösen könnte.

---

> * [ ]  Die "leader" Information ein mal in der KW-Spalte angeben (ist zum Großteil nach Wochen aufgeteilt, nach jedem Topic scheint mir zu viel Redundanz). Bei der einen Ausnahme am Anfang könnte man den Hinweis anpassen: "Gemeinsames Kick-Off mit Carsten und Canan".

Das gilt für uns, aber leider nicht für andere LVs, wo ich das nutzen wollte.

Ich könnte mir eine zusätzliche Variable vorstellen:

```
- week: "KW40"
  lecture:
    - topic: "/misc/syllabus"
      leader: "Leader für diese Lesson, geht in die VL-Spalte zur Lesson"
  leader: "gemeinsamer Leader, geht in die Wochen-Spalte"
  misc:
    - page: "/misc/resources"
      notes: "Vortrag Thema I"
    - notes: "Coden mit Edmonton"
    - page: "/misc/schedule"

```

Wenn diese belegt wird, dann erscheint der Text in der Wochen-Spalte. Wenn die derzeitigen "leader" nicht gesetzt werden, dann fällt dieser Text in der Tabelle auch weg. Dann würde das für uns so funktionieren wie von Dir beschrieben und für die anderen LV, wo innerhalb einer Woche gewechselt wird, würde es auch immer noch funktionieren. Was denkst Du?

Machst Du mir dazu bitte auch ein Ticket im https://github.com/cagix/Hugo-Lecture-Layouts auf?

---

> * [ ]  Zeilenumbruch zwischen Übungsblatt und (Abgabe xx); dadurch wird die Spalte schmaler.

Das sollte sich einfach umsetzen lassen :)  Machst Du mir bitte auch hierfür ein Ticket "drüben" auf?

---

> Ich habe diese Änderungen bereits umgesetzt und ausprobiert und kann diese ggfl. vor dem Mergen pushen.

Das Layout (also Styles und Shortcodes/Partials und Page-Templates) hatte ich ja zwecks Wiederverwendbarkeit in ein eigenes Repo ausgelagert. Kannst Du diese Änderungen bitte dort als Pull-Request einreichen und vorher je ein Ticket neu aufmachen, damit man die Änderungen zuordnen kann?

2021-09-08 14:22 UTC, cyildiz commented
Ich habe die einzelnen Tickets aufgemacht und werde demnächst die Änderungen dort pushen. 

Ich arbeite dann in diesem Branch weiter und ergänze die restliche Struktur...

2021-09-08 14:25 UTC, cagix commented
> Ich habe die einzelnen Tickets aufgemacht und werde demnächst die Änderungen dort pushen.
> 
> Ich arbeite dann in diesem Branch weiter und ergänze die restliche Struktur...

+1 :)

Kannst Du schon sagen, wofür Du bereits Änderungen hast? Dann könnte ich die anderen Vorschläge parallel umsetzen?

2021-09-08 14:26 UTC, cagix commented
PS: Ich habe Dir den PR mal "umgehängt" (assigned), da Du hier drin weiter arbeiten wirst. Wenn Du fertig bist, kannst Du mich ja wieder assignen, dann weiss ich, dass ich drüber schauen und merge kann.

2021-09-08 14:29 UTC, cyildiz commented
> Kannst Du schon sagen, wofür Du bereits Änderungen hast? Dann könnte ich die anderen Vorschläge parallel umsetzen?

Ich habe eigentlich alle schon umgesetzt. Kann sie schnell pushen und zum Review öffnen?

2021-09-08 14:49 UTC, cagix commented
> > Kannst Du schon sagen, wofür Du bereits Änderungen hast? Dann könnte ich die anderen Vorschläge parallel umsetzen?
> 
> Ich habe eigentlich alle schon umgesetzt. Kann sie schnell pushen und zum Review öffnen?

ja, bitte. du bist als collaborator eingetragen, du solltest also direkt feature-branches in das repo pushen können :)

2021-09-08 14:52 UTC, cagix commented
> > > Kannst Du schon sagen, wofür Du bereits Änderungen hast? Dann könnte ich die anderen Vorschläge parallel umsetzen?
> > 
> > 
> > Ich habe eigentlich alle schon umgesetzt. Kann sie schnell pushen und zum Review öffnen?
> 
> ja, bitte. du bist als collaborator eingetragen, du solltest also direkt feature-branches in das repo pushen können :)

du musst halt nur das andere repo nochmal extra klonen (im submodule ist nur die https-adresse drin) und dort einzelne feature-branches aufmachen und dann darin die einzelnen änderungen am besten einzeln rüberkopieren und dann pushen.

danach bitte nicht vergessen, im ordner `layouts/` ein `git checkout -- .` zu machen, damit das submodule wieder zurückgesetzt wird. sonst gibts beim nächsten update probleme ...

2021-09-11 13:25 UTC, cagix commented
@cyildiz die submodules in einem pr zu aktualisieren geht, kann aber probleme machen, wenn parallel im master das submodule auch bereits aktualisiert wurde. ein einfache rebasen hätte gereicht ;)

2021-09-11 13:25 UTC, cagix commented
@cyildiz wenn du fertig bist, bitte einfach an mich assignen zum mergen :)

2021-09-18 14:06 UTC, cagix commented
`data/schedule.yaml` wurde bereits an anderer stelle aktualisiert, dieser pr ist obsolet.

2021-09-18 14:06 UTC, closed without merging